version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16  
    commands:
      - echo Installing Mocha...
      - npm install -g mocha
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code starts
      - echo Compiling the Node.js code ends
      - echo Build ended on `date`
  post_build:
    commands:
      - echo Build completed on `date`
